FROM postgres:13

ENV POSTGRES_DB = mensajeria
ENV POSTGRES_USER=admin@admin.com
ENV POSTGRES_PASSWORD=pg123


COPY mensajeria.sql /docker-entrypoint-mensajeria.d/
COPY seepdate.sql /docker-entrypoint-mensajeria.d/